on:
  push:
    branches:
    - main
name: ci
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wntrblm/nox@2022.11.21
        with:
          python-versions: "3.7, 3.8, 3.9, 3.10, 3.11"
      - run: nox -s lint